### ISSUE TITLE
Missing pan limits configuration in gtunedesktop

### ISSUE THREAD

**Issue by remibiche** [Gremsy/gTuneDesktop#1]
Hi,
I do not see any interface in order to configure the pan limits values on the gtunedesktop v1.4.8.1 (tilt and roll limits configuration are available). Did I miss something ? If not, is it possible to add it ?

**Comment by gremsyQuanLe** [comment]
Hi,
Currently, the software only supports configure the tilt and roll limits. If you have problems connecting to gimbal, please contact https://gremsy.com/support for assistance. Thank you!
