### ISSUE TITLE
gTuneDesktop using Wine

### ISSUE THREAD

**Issue by julled** [Gremsy/gTuneDesktop#2]
Hi, 
i try to use the app on  a linux machine with a T3V3. I can connect to mapped USB Serial Port in wine, but then gtunedesktop freezes  and doesnt allow any control. Do you have tips how to fix this?

Thanks a lot,

**Comment by gremsyQuanLe** [comment]
Hi guys!
You can contact support for better support https://gremsy.com/support !
Thanks a lot.
