### ISSUE TITLE
Gremsy MIO gimbal

### ISSUE THREAD

**Issue by olorinum** [Gremsy/gTuneDesktop#3]
[Mio-Firmware-7.7.3_Official (1).zip](https://github.com/Gremsy/gTuneDesktop/files/14545858/Mio-Firmware-7.7.3_Official.1.zip)
Hello, 
Our company develops copters for cinema operators. We have decided to use MIO gimbal with our a custom-build cameras (mass is 230g)
We use 50V supply voltage and S-bus control.
Our customer requires us to speed up stabilization time for 90-degree TILT (down) position. At the moment (depending on particular gimbal set) this stabilization takes 30 … 90 seconds. 
In FOLLOW MODE we set the command to set 90-degree (rather “hot-key” or smooth stick down) and see gimbal moves down till the “edge”. Afterwards stabilization begins: gimbal start to slowly move on certain direction (aka fine adjustment) – for some gimbals this is about few degrees up, for some few degrees down, for some right and down and so on.
We have done STIFFNESS TUNING according to MIO User Manual.
Do you have an instruction or recommendation how to reduce this stabilization time to 10 … 15 seconds? We have observed that reduction of GYRO TRUST helps a bit but also has a negative side-effect.
We also need to know if this effect (direction of stabilization) is unique for each gimbal set or there is a way to have similar “direction” for all gimbals we are going to use.
Profile which we use is attached to the letter,
Thanks

**Comment by gremsyQuanLe** [comment]
Hi guys!
You can contact support for better support https://gremsy.com/support !
Thanks a lot.
